### ISSUE TITLE
[FEAT] Enable Survey Modification after Loading JSON

### ISSUE THREAD

**Issue by 3wweiweiwu** [Valires/streamlit-survey#14]
## Is your feature request related to a problem? Please describe.
Currently, I am working on a long survey. I want to enable user to save their state in json, close their browser, and use their json to resume their survey later. However, after I use from_json() function to load the survey state, I can no longer make change to the survey.

## Describe the solution you'd like
I want to be able to continue to work on survey after loading existing json.

## Describe alternatives you've considered
n/a

**Comment by 3wweiweiwu** [comment]
Close comment. It's my problem. Sorry for the confusion.

**Comment by OlivierBinette** [comment]
Hi @3wweiweiwu, do you think there should be more flexibility in how JSON is loaded? E.g. if there's missing fiels in the JSON, they just get NA values?
